### ISSUE TITLE
Kernel modules incompatible to current packages

### ISSUE THREAD

**Issue by dragetd** [brunompena/zsun-resources#2]
When trying to install any kernel module, opkg complains about the kernel not being the right version:
The installed version of package kernel is not compatible, require 4.14.151-1-b84a5a29… while 4.14.151-1-9631b106… is installed

Even with --force-depends the modules do not load. E.g. the fuse module fails like this:
```
[  973.658695] kmodloader: loading kernel modules from /etc/modules.d/*
[  973.776404] fuse: Unknown symbol forget_all_cached_acls (err 0)
[  973.781201] fuse: Unknown symbol posix_acl_default_xattr_handler (err 0)
[  973.787956] fuse: Unknown symbol posix_acl_from_xattr (err 0)
[  973.793885] fuse: Unknown symbol posix_acl_access_xattr_handler (err 0)
[  973.800042] fuse: Unknown symbol posix_acl_to_xattr (err 0)
[  973.814402] fuse: Unknown symbol forget_all_cached_acls (err 0)
[  973.819032] fuse: Unknown symbol posix_acl_default_xattr_handler (err 0)
[  973.826063] fuse: Unknown symbol posix_acl_from_xattr (err 0)
[  973.831870] fuse: Unknown symbol posix_acl_access_xattr_handler (err 0)
[  973.838036] fuse: Unknown symbol posix_acl_to_xattr (err 0
```

**Comment by brunompena** [comment]
**Please use the [OpenWrt forums](https://forum.openwrt.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331) for support.**

Because we're running a custom build you'll have to manually build any kernel modules you may require.
Please refer to [Build Guide](https://github.com/brunompena/zsun-resources/blob/master/README.md#build-guide) to get a working build environment.
